config/routes.rb
WishList::Application.routes.draw do
  root "welcome#index"
  resources :wishes, except: :index do
    collection do
      post :upload
      get :duoshuo_comments
    end

    member do
      post :grant
      post :confirm_grant

    end
  end

  resources :users
  resources :notifications, only: [:index, :show, :destroy]
  get 'auth/weibo/callback' => 'auth#weibo_login', as: :weibo_login
  get 'sign_out' => 'auth#sign_out', :as => :sign_out
end

app/models/wish.rb
# coding: utf-8
class Wish < ActiveRecord::Base
  include UUID
  include QnUploader
  include Rails.application.routes.url_helpers

  validates_presence_of :content

  mount_uploader :photo
  
  has_many :wishers
  has_one :achiever, class_name: "User", foreign_key: "achiever_id"
  belongs_to :user, counter_cache: true

  validates_inclusion_of :status, :in => %w(PENDING LOCKED GRANTED FAILED)

  scope :granted, -> { where(status: "GRANTED").includes(:user) }
  scope :pending, -> { where(status: "PENDING").includes(:user) }
  scope :locked, -> { where(status: "LOCKED").includes(:user) }
  scope :failed, -> { where(status: "FAILED").includes(:user) }

  %w(PENDING LOCKED GRANTED FAILED).each do |status|
    define_method :"#{status.downcase}?" do
      self.status == status
    end
  end

  def current_wisher
    self.wishers.where(current: true).first.try(:user)
  end

  after_create do
    self.delay(queue: "sync_2_weibo", priority: 20)
        .sync_2_weibo
  end

  after_update do
    return unless self.changed.include?('status')
    case self.status
    when "LOCKED"
      self.delay(queue: "send_grant_notification", priority: 20)
          .send_grant_notification
    when "GRANTED"
      self.delay(queue: "send_confirm_granted_notification", priority: 20)
          .send_confirm_granted_notification
    end
  end

  def sync_2_weibo
    str = "刚刚许了个心愿：『#{self.content.truncate(100)}』,谁能帮我？#{wish_url(self.id)}"
    opts = {
      :access_token => self.user.weibo_token,
      :status => URI.encode(str)
    }

    if self.photo.blank?
      pic_path = convert_to_tempfile(self.user.avatar_url).path
    else
      pic_path = convert_to_tempfile(self.photo_url).path
    end

    opts.merge!(:pic => Faraday::UploadIO.new(pic_path, 'image/jpeg'))
    conn = Faraday.new(:url => "https://upload.api.weibo.com") do |faraday|
      faraday.request :multipart 
      faraday.adapter :net_http
    end
    conn.post "/2/statuses/upload.json", opts         
  end

  def send_grant_notification
    return if user_id == current_wisher.id
    notify = Notification::Grant.new
    notify.user_id = current_wisher.id
    notify.to_user_id = self.user_id
    notify.model_id = self.id
    notify.save
  end

  def send_confirm_granted_notification
    return if user_id == current_wisher.id
    notify = Notification::ConfirmGrant.new
    notify.user_id = self.user_id
    notify.to_user_id = current_wisher.id
    notify.model_id = self.id
    notify.save
  end  

end

app/controllers/wishes_controller.rb
# coding: utf-8
class WishesController < ApplicationController
  before_action :require_login, except: [:index, :show, :duoshuo_comments]

  def index
    
  end

  def show
    @wish = Wish.find params[:id]
    @wisher = @wish.current_wisher
    set_seo_meta("#{@wish.user.name}的愿望", "#{@wish.content}", "#{@wish.content}")
  end

  def duoshuo_comments
    url = "http://api.duoshuo.com/threads/counts.json?short_name=yuanwang&threads=#{params[:wish_ids]}"
    resp = begin 
      req = Faraday.get url
      MultiJson.load(req.body) 
    rescue => e
      {"response" => {}}
    end
    @ret = {}
    resp["response"].each { |k, v| @ret[k] = v["comments"] }
    render :text => @ret.to_json
  end  

  def new
    require 'number_to_cn'
    @wish = current_user.wishes.new
    @current_count = (current_user.wishes_count + 1).to_cn_words
  end

  def create
    @wish = current_user.wishes.build wish_params
    if @wish.save
      redirect_to wish_path(@wish), success: "刚刚成功的许下了心愿"
    else
      redirect_to :back, alert: @wish.errors.full_message.first
    end
  end

  def upload
    wish = Wish.new
    wish.photo = params[:upload]
    render :text => { preview: wish.photo_url(:small), photo: wish.photo }.to_json
  end

  def grant
    @wish = Wish.find params[:id]
    if @wish.user == current_user
      message = { error: "不能认领自己的愿望" }
    else
      @wish.wishers.create(user_id: current_user.id, current: true)
      message = { success: "刚刚认领了 #{@wish.user.name} 的愿望，说到就要做到" }
    end
    redirect_to :back, message
  end

  def confirm_grant
    @wish = Wish.find params[:id]
    @wish.update_attribute(:status, "GRANTED")
    redirect_to :back, success: "恭喜你实现了这个愿望"
  end

  def edit
    
  end

  def update
    
  end

  def patch
    
  end

  def destroy
    
  end

  private

  def wish_params
    params.require(:wish).permit(:content, :photo, :deadline, :refer_link)
  end
end

app/views/wishes/new.html.slim
- content_for :head do
  = stylesheet_link_tag 'wishes'
  = javascript_include_tag 'wishes'

.wishes.container
  .new-wish
    h1 
      i.icon-gift
      span.ml-5 许下我的第『#{@current_count}』个愿望
    = form_for @wish, html: { :class => "form-horizontal" } do |f|
      .control-group        
        .controls
          = f.text_area :content, required: true, placeholder: "描述一下你的愿望"
      .control-group        
        .controls
          .input-prepend
            span.add-on: i.icon-shopping-cart
            = f.text_field :refer_link, :class => "span6", :placeholder => "甚至告诉TA在哪可以买到，输入购买链接"
      .control-group
        .controls    
         .btn.btn-large.btn-primary.fileinput-button type="file"
            i.icon-picture
            span.ml-5 上传一张图片
            input#fileupload type="file" name="upload"
            span.ml-5.loading.hide
              i.icon-spinner.icon-spin            
            = f.hidden_field :photo
      .control-group        
        .controls
          .input-prepend
            span.add-on: i.icon-time
            input#deadline.span3 type="date" name="deadline" placeholder="希望在指定时间之前实现"

      .control-group.mt-30 
        .controls
          button.btn.btn-info.btn-large
            i.icon-ok
            span.ml-5 发布我的愿望                 

app/views/wishes/show.html.slim
- content_for :head do
  = stylesheet_link_tag 'wishes'
  = javascript_include_tag 'wishes'
.wishes.container
  .wish
    .user.clearfix
      .from.pull-left.clearfix
        .avatar.pull-left
          a href="#{user_path(@wish.user)}"
            img src="#{@wish.user.avatar_url(:tiny)}"
        .name.ml-5.pull-left
          a href="#{user_path(@wish.user)}"= @wish.user.name

      .wish-status.pull-left
        = wish_status_tag(@wish)  
       
      .to.pull-right.clearfix
        .avatar.pull-left
          = grant @wish do
            - if @wish.pending? 
              = image_tag "avatar/tiny.jpg"
            - else
              img src="#{@wisher.avatar_url(:tiny)}"
        .name.ml-5.pull-left
          = grant @wish do
            = @wish.pending? ? "点击认领#{@wish.user.name}的愿望" : @wisher.name

    .wish-detail
      - if confirmable?(@wish)
        .confirm.mt-20.mb-20
          a.btn.btn-info.btn-large.btn-block href="#{confirm_grant_wish_path(@wish)}" data-method="POST"
            i.icon-ok
            span.ml-5 点此确认 『#{@wish.current_wisher.name}』 实现你了的愿望
      .detail.mt-20
        .content 
          = @wish.content
        .photo.mb-20.mt-20
          a href="#{@wish.photo_url}" target="_blank"
            img src="#{@wish.photo_url(:normal)}"
        .tools.clearfix 
          .pull-right
            - if @wish.refer_link.present?
              p
                i.icon-shopping-cart
                a.ml-5 href="#{format_link @wish.refer_link}" target="_blank"= @wish.refer_link
            - if @wish.deadline.present?
              p
                i.icon-time
                span.ml-5 希望在
                spam.label.ml-5= @wish.deadline.strftime('%F %T')
                span.ml-5 前实现

      .comment
        = render "shared/duoshuo"                