config/routes.rb
WishList::Application.routes.draw do
  root "welcome#index"
  resources :wishes, except: :index do
    collection do
      post :upload
      get :duoshuo_comments
    end

    member do
      post :grant
      post :confirm_grant

    end
  end

  resources :users
  resources :notifications, only: [:index, :show, :destroy]
  get 'auth/weibo/callback' => 'auth#weibo_login', as: :weibo_login
  get 'sign_out' => 'auth#sign_out', :as => :sign_out
end

app/models/notification/base.rb
# coding: utf-8
class Notification::Base < ActiveRecord::Base
  self.table_name = "notifications"

  validates_presence_of :user_id, :to_user_id

  belongs_to :user
  belongs_to :to_user, :class_name => "User", :foreign_key => :to_user_id

  scope :unread, -> { where(readed: false) }
end

app/models/notification/confirm_grant.rb
# coding: utf-8
class Notification::ConfirmGrant < Notification::Base
  belongs_to :wish, class_name: "Wish", foreign_key: "model_id"
end

app/models/notification/grant.rb
# coding: utf-8
class Notification::Grant < Notification::Base
  belongs_to :wish, class_name: "Wish", foreign_key: "model_id"
end

app/controllers/notifications_controller.rb
# coding: utf-8
class NotificationsController < ApplicationController
  before_action :require_login
  after_action :read_notifications, only: :index

  def index
    @notifications = current_user.received_notifications.order('created_at DESC')
  end

  def destroy
    notification = Notification::Base.find params[:id]
    notification.destroy
    redirect_to :back, warning: "消息已被删除"
  end

  private

  def read_notifications
    current_user.read_notifications @notifications
  end
end

app/views/notifications/notification/_confirm_grant.html.slim
.item.clearfix
  .pull-left.clearfix
    .status.pull-left class="#{notification.readed? ? "readed" : nil}"
      i.icon-circle

    .content.pull-left.ml-10        
      a href="#{user_path(notification.user)}"= notification.user.name
      span.ml-10 确认了你完成了TA的愿望
      a.ml-10 href="#{wish_path(notification.wish)}"= notification.wish.content.truncate(30)
  .pull-right.clearfix
    .avatar.pull-left
      a href="#{user_path(notification.user)}"
        img src="#{notification.user.avatar_url(:tiny)}" width="20" 
    .datetime.pull-left.ml-10
      span.label= notification.created_at.strftime('%F %T')           
    .delete.pull-left.ml-10
      a.label.label-important href="#{notification_path(notification)}" data-method="DELETE" 删除

app/views/notifications/notification/_grant.html.slim
.item.clearfix
  .pull-left.clearfix
    .status.pull-left class="#{notification.readed? ? "readed" : nil}"
      i.icon-circle

    .content.pull-left.ml-10        
      a href="#{user_path(notification.user)}"= notification.user.name
      span.ml-10 认领了你的愿望
      a.ml-10 href="#{wish_path(notification.wish)}"= notification.wish.content.truncate(30)
  .pull-right.clearfix
    .avatar.pull-left
      a href="#{user_path(notification.user)}"
        img src="#{notification.user.avatar_url(:tiny)}" width="20" 
    .datetime.pull-left.ml-10
      span.label= notification.created_at.strftime('%F %T')           
    .delete.pull-left.ml-10
      a.label.label-important href="#{notification_path(notification)}" data-method="DELETE" 删除