config/routes.rb
WishList::Application.routes.draw do
  root "welcome#index"
  resources :wishes, except: :index do
    collection do
      post :upload
      get :duoshuo_comments
    end

    member do
      post :grant
      post :confirm_grant

    end
  end

  resources :users
  resources :notifications, only: [:index, :show, :destroy]
  get 'auth/weibo/callback' => 'auth#weibo_login', as: :weibo_login
  get 'sign_out' => 'auth#sign_out', :as => :sign_out
end

app/models/user.rb
# coding: utf-8
class User < ActiveRecord::Base
  include UUID
  include QnUploader

  validates :name, presence: true, length: { maximum: 40, minimum: 2 }
  validates :email, presence: true, uniqueness: true
  validates_uniqueness_of :weibo_uid, allow_blank: true

  has_secure_password
  mount_uploader :avatar

  has_many :wishes, -> { order('created_at DESC') }
  has_many :wishers
  has_many :received_notifications, class_name: "Notification::Base", foreign_key: "to_user_id"

  def self.build_via_weibo(auth)
    user = User.new
    user.name = auth['name']
    user.password_confirmation = user.password = SecureRandom.hex(4)
    auth['avatar_url'] << "/sample.jpg" unless auth['avatar_url'].end_with?('.jpg')
    user.avatar = auth['avatar_url']
    user.email = "#{auth['weibo_uid']}@weibo.com"
    user.weibo_uid = auth['weibo_uid']
    user.weibo_token = auth['weibo_token']
    user   
  end

  def unread_notifies_count
    self.received_notifications.where(readed: false).count
  end

  def grant_wishes
    Wish.where(id: self.wishers.map(&:wish_id))
  end

  def read_notifications(notifications)
    unread_ids = notifications.where(readed: false).pluck(:id)
    if unread_ids.any?
      Notification::Base.where({ id: unread_ids, readed: false }).update_all(readed: true)
    end    
  end  
end

app/controllers/users_controller.rb
# coding: utf-8
class UsersController < ApplicationController
  def show
    @user =  User.find params[:id]
    if params[:list] == 'grant'
      @wishes = @user.grant_wishes.includes('wishers')
    else
      @wishes = @user.wishes.includes('wishers')
      @wishes = @wishes.send(params[:list]) unless params[:list].blank?
    end     
    @wishes = @wishes.order('wishes.created_at DESC')
    set_seo_meta("#{@user.name}的愿望清单", "愿望清单", "愿望清单")
  end

end

app/views/users/show.html.slim
- content_for :head do
  = stylesheet_link_tag 'users'

.users.container
  .info.clearfix
    .avatar.pull-left
      img src="#{@user.avatar_url(:normal)}"        
    .detail.pull-left
      p
        a href="#"= @user.name
        a.ml-10 href="http://weibo.com/u/#{@user.weibo_uid}" target="_blank": i.icon-weibo
      p
        i.icon-gift 
        a.ml-10= @user.wishes_count
      p
        i.icon-heart
        a.ml-10= @user.grant_wishes.count      
      / p
      /   small Right here waiting...
  .wish-list.mt-20
    ul.nav.nav-tabs
      li class="#{params[:list].blank? ? 'active' : nil}"
        a href="#{user_path(@user)}"
          i.icon-gift
          span.ml-5 所有

      - %w(PENDING LOCKED GRANTED FAILED).each do |status|
        li class="#{(params[:list] || '').upcase == status ? 'active' : nil}"
          a href="#{user_path(@user, list: status.downcase)}"
            i class="#{icon(status)}"
            span.ml-5= text(status)
      li class="#{params[:list] == 'grant' ? 'active' : nil}"
        a href="#{user_path(@user, list: 'grant')}"
          i.icon-heart
          span.ml-5 认领的                    
    .wish-items
      - @wishes.each do |wish|
        .item.clearfix
          .wish-status.pull-left
            a href="#{wish_path(wish)}"
              - if wish.granted?
                i.icon-check
              - else
                i.icon-check-empty  
          .wish-content.pull-left
            a.ml-10 href="#{wish_path(wish)}"
              span.label class="label-#{color(wish.status)}"
                = wish.content.truncate(40)
          .wish-info.pull-right
            - if wish.current_wisher.present?
              a href="#{user_path(wish.current_wisher)}" data-original-title="被 [#{wish.current_wisher.name}] 认领了" title="被 [#{wish.current_wisher.name}] 认领了" data-toggle="tooltip"
                img src="#{wish.current_wisher.avatar_url(:tiny)}" width="20"
            - if wish.refer_link.present?
              a.ml-10 data-original-title="#{wish.refer_link}" title="#{wish.refer_link}" data-toggle="tooltip" href="#{wish_path(wish)}"
                i.icon-shopping-cart
            - if wish.photo.present?
              a.ml-10 href="#{wish_path(wish)}"
                i.icon-picture
            - if true           
              a.ml-10 href="#{wish_path(wish)}"
                i.icon-comment 
                span.ml-5 class="comment_#{wish.id}" ...
            - if wish.deadline.present?
              a.ml-10 data-original-title="截止 #{wish.deadline.strftime('%F')}" title="截止 #{wish.deadline.strftime('%F')}" data-toggle="tooltip" href="#{wish_path(wish)}"
                i.icon-time
            a.ml-10 href="#{wish_path(wish)}" data-original-title="#{text(wish.status)}" title="#{text(wish.status)}" data-toggle="tooltip"
              i class="#{icon(wish.status)}"
javascript:
  $(function () {
    var wish_ids = "#{@wishes.map(&:id).join(',')}";
    var url = "/wishes/duoshuo_comments/";
    $.get(url, {wish_ids: wish_ids}, function (res) {
      $.each(res, function (i, val) {
        $('.comment_'+i).text(val);
      });
    }, 'json');
  });