config/routes.rb
WishList::Application.routes.draw do
  root "welcome#index"
  resources :wishes, except: :index do
    collection do
      post :upload
      get :duoshuo_comments
    end

    member do
      post :grant
      post :confirm_grant

    end
  end

  resources :users
  resources :notifications, only: [:index, :show, :destroy]
  get 'auth/weibo/callback' => 'auth#weibo_login', as: :weibo_login
  get 'sign_out' => 'auth#sign_out', :as => :sign_out
end

app/views/layouts/application.html.slim
<!DOCTYPE html>
html
  head
    = render_page_title
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = yield :head
    = csrf_meta_tags
    meta name='keywords' content="#{@keywords}"
    meta name='description' content="#{@description}"    
    = favicon_link_tag "favicon.ico"
  body
    .header
      .navbar.navbar-inverse.navbar-static-top
        .navbar-inner
          .pull-left
            .nav-collapse.collapse
              a.brand href="#{root_path}" 
                = image_tag 'logo.png'
              ul.nav
                li class="#{params[:list].blank? ? 'active' : nil}": a href="#{root_path}" 所有
                li class="#{params[:list] == 'granted' ? 'active' : nil}": a href="#{root_path(list: 'granted')}" 已完成的
                li class="#{params[:list] == 'locked' ? 'active' : nil}": a href="#{root_path(list: 'locked')}" 已认领的
                li class="#{params[:list] == 'pending' ? 'active' : nil}": a href="#{root_path(list: 'pending')}" 未认领的             
          .pull-right
            ul.nav
              li: a href="#{new_wish_path}" 
                i.icon-edit
                span.ml-5 许一个愿望
              - if signed_in?            
                li: a href="#{user_path(current_user)}"= current_user.name
                li: a href="#{notifications_path}"
                  = render_notify_label
                li.sign_out
                  a href="#{sign_out_path}"
                    i.icon-power-off
              - else
                li: a href="/auth/weibo" 
                  i.icon-weibo
                  span.ml-5 登录
    .container.clearfix
      = render_notice_message    
    .main
      = yield
    .footer.container
      a href="https://twitter.com/jim_hj" 
        i.icon-twitter
        span.ml-5 @jim_hj